"""create users table

Revision ID: 10a18afeb713
Revises: 
Create Date: 2026-04-12 17:29:26.672920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '10a18afeb713'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('user_type', sa.Enum('citizen', 'building_admin', 'recycler', 'eca_operator', 'asobeum_admin', 'b2b_client', name='usertype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('building_name', sa.String(length=255), nullable=True),
    sa.Column('num_units', sa.Integer(), nullable=True),
    sa.Column('representation_document', sa.Text(), nullable=True),
    sa.Column('id_number', sa.String(length=20), nullable=True),
    sa.Column('profile_picture', sa.Text(), nullable=True),
    sa.Column('id_picture', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.Enum('pending', 'verified', 'rejected', name='verificationstatus'), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('employee_code', sa.String(length=50), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('association_nit', sa.String(length=50), nullable=True),
    sa.Column('legal_representative', sa.String(length=255), nullable=True),
    sa.Column('coverage_area', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('commercial_contact', sa.String(length=255), nullable=True),
    sa.Column('rep_goals', sa.JSON(), nullable=True),
    sa.Column('association_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tax_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id_number'), 'users', ['id_number'], unique=True)
    op.execute("CREATE INDEX idx_users_coverage_area ON users USING GIST (coverage_area)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS idx_users_coverage_area")
    op.drop_index(op.f('ix_users_id_number'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
